"""
seed_data.py
------------
Données de référence manuellement vérifiées pour Paris Nord Villepinte.
Ces données servent de base fiable et sont fusionnées avec les résultats
du scraping automatique.

À mettre à jour manuellement 1-2 fois par an si besoin.
"""

SEED_EVENTS = [
    {
        "nom": "JEC World",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-03-10",
        "date_fin":   "2026-03-12",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Industrie / Matériaux composites",
        "periodicite": "annuel",
        "visiteurs_total": 45000,
        "nb_places": 80000,
        "population": "Ingénieurs R&D, industriels (aéro, auto, énergie), acheteurs internationaux — 35-55 ans, CSP++, 60% international",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "1er salon mondial des matériaux composites. 1 500 exposants, 60+ pays, conférences techniques et remises de prix innovation.",
        "commentaire": "Clientèle internationale avec budgets pris en charge. Forte demande hôtels 4★ proches CDG. Tarif estimé +35 à +50%.",
        "source": "seed",
    },
    {
        "nom": "Paris Manga & Sci-Fi Show",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-03-14",
        "date_fin":   "2026-03-15",
        "type_evenement": "Expo Grand Public",
        "secteur": "Culture / Pop culture / Manga",
        "periodicite": "bi-annuel",
        "visiteurs_total": 70000,
        "nb_places": 90000,
        "population": "Passionnés manga, cosplay, jeux vidéo — 15-30 ans, majorité francophone, budget serré",
        "evenement_pro": "Non",
        "importance": "med",
        "description": "Un des plus grands festivals pop culture en France, 39e édition. Manga, BD, jeux vidéo, cosplay, exclusivité mondiale Disney+.",
        "commentaire": "Public jeune, budget limité. Forte pression Airbnb et hôtels 2-3★. Tarif estimé +20 à +35%.",
        "source": "seed",
    },
    {
        "nom": "Global Industrie + SITL",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-03-30",
        "date_fin":   "2026-04-02",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Industrie de production / Logistique / Supply chain",
        "periodicite": "annuel",
        "visiteurs_total": 80000,
        "nb_places": 150000,
        "population": "Dirigeants industriels, ingénieurs, directeurs achats et supply chain — 40-60 ans, CSP++, fort taux international",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "1er salon européen des technologies de production (Industrie Paris + TOLEXPO + Smart Industries) co-localisé avec SITL.",
        "commentaire": "Double salon sur 4 jours. Frais pris en charge par les entreprises. Saturation hôtels 3-4★ dans un rayon 20 km. Tarif estimé +45 à +65%.",
        "source": "seed",
    },
    {
        "nom": "Eurosatory",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-06-15",
        "date_fin":   "2026-06-19",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Défense terrestre / Sécurité internationale",
        "periodicite": "biennal",
        "visiteurs_total": 60000,
        "nb_places": 120000,
        "population": "Militaires hauts gradés, ministres, délégations gouvernementales 150+ pays, industriels défense — CSP+++, per diem institutionnels très élevés",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "Salon de référence mondiale pour la défense terrestre. 1 700 exposants, 63 pays, délégations officielles de 150+ États. Biennal.",
        "commentaire": "Clientèle ultra-institutionnelle. Réservations bloquées des mois à l'avance. Impact sur toute l'IDF. Tarif estimé +60 à +90%.",
        "source": "seed",
    },
    {
        "nom": "Japan Expo Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-07-09",
        "date_fin":   "2026-07-12",
        "type_evenement": "Expo Grand Public",
        "secteur": "Culture japonaise / Gaming / Musique / Loisirs",
        "periodicite": "annuel",
        "visiteurs_total": 250000,
        "nb_places": 300000,
        "population": "Fans de culture japonaise, gamers, amateurs d'animés — 15-35 ans, Europe entière, familles et touristes étrangers",
        "evenement_pro": "Non",
        "importance": "high",
        "description": "Plus grand festival européen de culture japonaise, 25e édition. Manga, gaming, gastronomie, J-music, arts martiaux, cosplay.",
        "commentaire": "Volume exceptionnel. Saturation totale des hébergements proches. Airbnb saturé dès J-60. Tarif estimé +30 à +55%.",
        "source": "seed",
    },
    {
        "nom": "Première Vision Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-09-01",
        "date_fin":   "2026-09-03",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Mode / Textile premium / Luxe",
        "periodicite": "bi-annuel",
        "visiteurs_total": 55000,
        "nb_places": 80000,
        "population": "Créateurs, directeurs artistiques, acheteurs mode et luxe — 25-50 ans, très international (Europe, Asie, USA), CSP++",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "Salon international de référence pour les matières premières de la mode (tissus, cuirs, fils, accessoires de luxe). 2 éditions/an.",
        "commentaire": "Concomitant Fashion Week Paris → semaine la plus chère de l'année. Tarif estimé +70 à +100%.",
        "source": "seed",
    },
    {
        "nom": "Maison & Objet Septembre",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-09-10",
        "date_fin":   "2026-09-14",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Design / Décoration / Art de vivre",
        "periodicite": "bi-annuel",
        "visiteurs_total": 85000,
        "nb_places": 150000,
        "population": "Architectes d'intérieur, décorateurs, acheteurs retail design — 30-55 ans, très international, CSP++",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "Carrefour mondial du design et de la décoration. 3 000 exposants, 60 pays. L'un des salons pro les plus influents mondialement.",
        "commentaire": "5 jours, clientèle internationale premium. Taux occupation ~100% dans rayon 20 km. Tarif estimé +50 à +75%.",
        "source": "seed",
    },
    {
        "nom": "SILMO Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-09-25",
        "date_fin":   "2026-09-28",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Optique / Lunetterie",
        "periodicite": "annuel",
        "visiteurs_total": 35000,
        "nb_places": 60000,
        "population": "Opticiens, ophtalmologues, acheteurs réseaux optique, industriels verres et montures — 35-60 ans, fort taux international",
        "evenement_pro": "Oui",
        "importance": "med",
        "description": "Salon international de référence de la filière optique-lunetterie. Organisé par l'association SILMO.",
        "commentaire": "Impact modéré mais concentré. Frais pris en charge. Tarif estimé +25 à +40%.",
        "source": "seed",
    },
    {
        "nom": "SIAL Paris 2026",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-10-17",
        "date_fin":   "2026-10-21",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Alimentation / Agroalimentaire / Restauration",
        "periodicite": "biennal",
        "visiteurs_total": 320000,
        "nb_places": 400000,
        "population": "Acheteurs GMS, directeurs import/export, chefs cuisiniers, industriels agroalimentaire — monde entier, tous budgets d'entreprise",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "L'un des 2 plus grands salons agroalimentaires mondiaux. 7 000 exposants, 127 pays, 5 jours, 100% B2B. Biennal.",
        "commentaire": "Impact hôtelier maximal. Saturation IDF entière. Prix fixés 12 mois à l'avance pour grands comptes. Tarif estimé +55 à +85%.",
        "source": "seed",
    },
    {
        "nom": "Euronaval",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-11-03",
        "date_fin":   "2026-11-06",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Défense navale / Sécurité maritime",
        "periodicite": "biennal",
        "visiteurs_total": 25000,
        "nb_places": 50000,
        "population": "Officiers de marine, industriels naval, délégations gouvernementales 50+ pays — très institutionnel, per diem élevés",
        "evenement_pro": "Oui",
        "importance": "med",
        "description": "Salon mondial de la défense navale et de la sécurité maritime. Marines nationales et industriels de 50+ pays. Biennal.",
        "commentaire": "Niche très premium. Per diem institutionnels élevés. Impact dans rayon 15 km. Tarif estimé +30 à +50%.",
        "source": "seed",
    },
    {
        "nom": "All4Pack Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2026-11-23",
        "date_fin":   "2026-11-26",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Emballage / Packaging / Process / Manutention",
        "periodicite": "biennal",
        "visiteurs_total": 55000,
        "nb_places": 90000,
        "population": "Responsables packaging, directeurs achat industrie, imprimeurs, logisticiens — 35-55 ans, fort taux international",
        "evenement_pro": "Oui",
        "importance": "med",
        "description": "Salon international des solutions d'emballage, impression, process et manutention. Biennal.",
        "commentaire": "Fin novembre généralement creuse → rapport demande/offre très favorable aux hôtels. Tarif estimé +35 à +55%.",
        "source": "seed",
    },
    {
        "nom": "Maison & Objet Janvier",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2027-01-14",
        "date_fin":   "2027-01-18",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Design / Décoration / Art de vivre",
        "periodicite": "bi-annuel",
        "visiteurs_total": 85000,
        "nb_places": 150000,
        "population": "Architectes d'intérieur, décorateurs, acheteurs retail design — 30-55 ans, très international, CSP++",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "Édition janvier de Maison & Objet. Même format que septembre. Période touristiquement creuse → impact relatif amplifié.",
        "commentaire": "Concurrence touristique quasi nulle en janvier. Hôtels complets 3-6 semaines avant. Tarif estimé +55 à +80%.",
        "source": "seed",
    },
    {
        "nom": "Intermat Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2027-04-24",
        "date_fin":   "2027-04-27",
        "type_evenement": "Expo Professionnelle",
        "secteur": "BTP / Génie civil / Construction",
        "periodicite": "triennal",
        "visiteurs_total": 200000,
        "nb_places": 300000,
        "population": "Entrepreneurs BTP, conducteurs de travaux, ingénieurs génie civil, acheteurs équipements lourds — 35-60 ans, fort taux international",
        "evenement_pro": "Oui",
        "importance": "high",
        "description": "Salon international de référence BTP/génie civil. 1 500+ exposants, acheteurs monde entier. Triennal — l'un des 5 plus grands salons de Villepinte.",
        "commentaire": "Triennal = rareté maximale. Très fort volume. Clientèle internationale avec frais pris en charge. Tarif estimé +50 à +75%.",
        "source": "seed",
    },
    {
        "nom": "Milipol Paris",
        "lieu": "Paris Nord Villepinte",
        "date_debut": "2027-11-16",
        "date_fin":   "2027-11-19",
        "type_evenement": "Expo Professionnelle",
        "secteur": "Sécurité intérieure / États / Forces de l'ordre",
        "periodicite": "biennal",
        "visiteurs_total": 30000,
        "nb_places": 60000,
        "population": "Forces de l'ordre, douaniers, services d'urgence, industriels sécurité — 160+ pays, très institutionnel, per diem gouvernementaux",
        "evenement_pro": "Oui",
        "importance": "med",
        "description": "Salon mondial de la sécurité intérieure des États, sous patronage du ministère de l'Intérieur. 160+ pays représentés. Biennal.",
        "commentaire": "Très institutionnel, niche mais premium. Impact notable dans rayon 15 km. Tarif estimé +30 à +50%.",
        "source": "seed",
    },
]
